services:
  mongo:
    image: mongo:7
    container_name: shopsmart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shopsmart-server
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/shopsmart
    depends_on:
      - mongo
    ports:
      - "5001:5001"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shopsmart-client
    ports:
      - "5173:8080"
    depends_on:
      - server

volumes:
  mongo_data:
